name       : libwebp
version    : 1.0.0
release    : 10
source     :
    - https://github.com/webmproject/libwebp/archive/v1.0.0.tar.gz : c5c5ebf979543ac1f3348df8f6245262abd787a147b9632c880d92bfc38dbbeb
homepage   : https://developers.google.com/speed/webp/
license    : BSD-2-Clause
component  : multimedia.codecs
emul32     : yes
summary    : A new image format for the web
description: |
    WebP is a new image format that provides lossless and lossy compression for images on the web. WebP lossless images are 26% smaller in size compared to PNGs. WebP lossy images are 25-34% smaller in size compared to JPEG images at equivalent SSIM index. WebP supports lossless transparency (also known as alpha channel) with just 22% additional bytes. Transparency is also supported with lossy compression and typically provides 3x smaller file sizes compared to PNG when lossy compression is acceptable for the red/green/blue color channels.
patterns   :
    - devel : /usr/share/man
builddeps  :
    - pkgconfig32(freeglut)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(zlib)
setup      : |
    %reconfigure --disable-static --enable-everything
build      : |
    %make
install    : |
    %make_install
